"""Add role links to AdministrativeDepartment

Revision ID: 04f426a09d38
Revises: b2aa5402b721
Create Date: 2025-10-30 16:02:16.571276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f426a09d38'
down_revision = 'b2aa5402b721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrative_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vice_role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('member_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['member_role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['head_role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['vice_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrative_department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_role_id')
        batch_op.drop_column('vice_role_id')
        batch_op.drop_column('head_role_id')

    # ### end Alembic commands ###
