"""Add Google Form IDs to Course

Revision ID: 40277024a952
Revises: af2526f6bb13
Create Date: 2025-11-12 16:42:21.725558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40277024a952'
down_revision = 'af2526f6bb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midterm_google_form_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('midterm_google_sheet_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('final_google_form_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('final_google_sheet_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('final_google_sheet_id')
        batch_op.drop_column('final_google_form_id')
        batch_op.drop_column('midterm_google_sheet_id')
        batch_op.drop_column('midterm_google_form_id')

    # ### end Alembic commands ###
