"""Add midterm remediated score to CourseGrade

Revision ID: 51e03913e151
Revises: d1a8f34cd452
Create Date: 2025-10-26 20:48:39.941631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e03913e151'
down_revision = 'd1a8f34cd452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midterm_remediated_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.drop_column('midterm_remediated_score')

    # ### end Alembic commands ###
