"""Add ms_remediated_status to CourseGrade

Revision ID: 5f940bbf1e8d
Revises: b3b045a29bf6
Create Date: 2025-10-14 11:29:14.435964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f940bbf1e8d'
down_revision = 'b3b045a29bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ms_remediated_status', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.drop_column('ms_remediated_status')

    # ### end Alembic commands ###
