"""Add attendance_date with default to AttendanceRecord

Revision ID: 64b65637fed6
Revises: b2b65da20faa
Create Date: 2025-10-09 12:40:34.285486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b65637fed6'
down_revision = 'b2b65da20faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_attendance_record')
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False))
        batch_op.drop_constraint(batch_op.f('_student_entry_uc'), type_='unique')
        batch_op.create_unique_constraint('_student_entry_date_uc', ['student_id', 'timetable_entry_id', 'attendance_date'])
        batch_op.create_index(batch_op.f('ix_attendance_record_attendance_date'), ['attendance_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_record_attendance_date'))
        batch_op.drop_constraint('_student_entry_date_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_student_entry_uc'), ['student_id', 'timetable_entry_id'])
        batch_op.drop_column('attendance_date')

    op.create_table('_alembic_tmp_attendance_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('timetable_entry_id', sa.INTEGER(), nullable=False),
    sa.Column('recorder_id', sa.INTEGER(), nullable=False),
    sa.Column('attendance_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['recorder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'timetable_entry_id', 'attendance_date', name=op.f('_student_entry_date_uc'))
    )
    # ### end Alembic commands ###
