"""Add level_group to GradeLevel

Revision ID: 7b76a297affd
Revises: e246ef5fbc1e
Create Date: 2025-10-12 14:34:30.363500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b76a297affd'
down_revision = 'e246ef5fbc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_course_submitted_by_user', 'user', ['submitted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_submitted_by_user', type_='foreignkey')

    # ### end Alembic commands ###
