"""Create CourseGrade table and remove exam scores from Enrollment

Revision ID: 908a62939512
Revises: 64b65637fed6
Create Date: 2025-10-11 09:58:03.338941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908a62939512'
down_revision = '64b65637fed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('midterm_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='_student_course_grade_uc')
    )
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_grade_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_grade_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('midterm_score')
        batch_op.drop_column('final_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('midterm_score', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_grade_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_grade_course_id'))

    op.drop_table('course_grade')
    # ### end Alembic commands ###
