"""Link SubUnit to AssessmentTopic

Revision ID: a0507f182cdf
Revises: 6a6946c8575c
Create Date: 2025-11-01 15:23:26.347883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0507f182cdf'
down_revision = '6a6946c8575c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subunit_topics',
    sa.Column('subunit_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subunit_id'], ['sub_unit.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['assessment_topic.id'], ),
    sa.PrimaryKeyConstraint('subunit_id', 'topic_id')
    )
    # op.drop_table('_alembic_tmp_administrative_department')
    with op.batch_alter_table('administrative_department', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['vice_role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['member_role_id'], ['id'])
        batch_op.create_foreign_key(None, 'role', ['head_role_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('ix_classroom_program_id'), ['program_id'], unique=False)
        batch_op.create_foreign_key(None, 'program', ['program_id'], ['id'])
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'])

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        #batch_op.drop_constraint(batch_op.f('_semester_grade_subject_uc'), type_='unique')
        batch_op.create_unique_constraint('_semester_grade_program_subject_uc', ['semester_id', 'grade_level_id', 'program_id', 'subject_id'])
        batch_op.create_foreign_key(None, 'program', ['program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_semester_grade_program_subject_uc', type_='unique')
        #batch_op.create_unique_constraint(batch_op.f('_semester_grade_subject_uc'), ['semester_id', 'grade_level_id', 'subject_id'])

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_index(batch_op.f('ix_classroom_program_id'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('administrative_department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    #op.create_table('_alembic_tmp_administrative_department',
    #sa.Column('id', sa.INTEGER(), nullable=False),
    #sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    #sa.Column('head_id', sa.INTEGER(), nullable=True),
    #sa.Column('vice_director_id', sa.INTEGER(), nullable=True),
    #sa.Column('head_role_id', sa.INTEGER(), nullable=True),
    #sa.Column('vice_role_id', sa.INTEGER(), nullable=True),
    #sa.Column('member_role_id', sa.INTEGER(), nullable=True),
    #sa.ForeignKeyConstraint(['head_id'], ['user.id'], ),
    #sa.ForeignKeyConstraint(['head_role_id'], ['role.id'], name=op.f('fk_admin_dept_head_role_id')),
    #sa.ForeignKeyConstraint(['member_role_id'], ['role.id'], name=op.f('fk_admin_dept_member_role_id')),
    #sa.ForeignKeyConstraint(['vice_director_id'], ['user.id'], ),
    #sa.ForeignKeyConstraint(['vice_role_id'], ['role.id'], name=op.f('fk_admin_dept_vice_role_id')),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('name')
    #)
    op.drop_table('subunit_topics')
    # ### end Alembic commands ###
