"""Add google_form_id google_sheet_id to GradedItem

Revision ID: af2526f6bb13
Revises: 4c9efa1e4506
Create Date: 2025-11-12 16:00:46.565975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2526f6bb13'
down_revision = '4c9efa1e4506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graded_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_form_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_sheet_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_graded_item_google_form_id'), ['google_form_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graded_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graded_item_google_form_id'))
        batch_op.drop_column('google_sheet_id')
        batch_op.drop_column('google_form_id')

    # ### end Alembic commands ###
