"""Add attendance_warning table

Revision ID: b2b65da20faa
Revises: 860f23fb5b04
Create Date: 2025-10-09 09:08:35.899709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b65da20faa'
down_revision = '860f23fb5b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('threshold_percent', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('absence_count_at_trigger', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'threshold_percent', name='_student_course_threshold_uc')
    )
    with op.batch_alter_table('attendance_warning', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_warning_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_warning_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_warning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_warning_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_warning_course_id'))

    op.drop_table('attendance_warning')
    # ### end Alembic commands ###
