"""Recreate course_grade table

Revision ID: b98abac45149
Revises: 5f940bbf1e8d
Create Date: 2025-10-14 12:31:09.397829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98abac45149'
down_revision = '5f940bbf1e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('midterm_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('final_grade', sa.String(length=10), nullable=True),
    sa.Column('remediation_status', sa.String(length=50), nullable=False),
    sa.Column('original_final_grade', sa.String(length=10), nullable=True),
    sa.Column('remediated_at', sa.DateTime(), nullable=True),
    sa.Column('ms_remediated_status', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='_student_course_grade_uc')
    )
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_grade_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_grade_final_grade'), ['final_grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_grade_student_id'), ['student_id'], unique=False)

    op.drop_table('_alembic_tmp_grade_level')
    op.drop_table('course_grade_temp')
    with op.batch_alter_table('grade_level', schema=None) as batch_op:
        batch_op.alter_column('level_group',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_level', schema=None) as batch_op:
        batch_op.alter_column('level_group',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('course_grade_temp',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('midterm_score', sa.REAL(), nullable=True),
    sa.Column('final_score', sa.REAL(), nullable=True),
    sa.Column('final_grade', sa.TEXT(), nullable=True),
    sa.Column('remediation_status', sa.TEXT(), nullable=True),
    sa.Column('original_final_grade', sa.TEXT(), nullable=True),
    sa.Column('remediated_at', sa.NUMERIC(), nullable=True),
    sa.Column('ms_remediated_status', sa.NUMERIC(), nullable=True)
    )
    op.create_table('_alembic_tmp_grade_level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=10), nullable=True),
    sa.Column('head_id', sa.INTEGER(), nullable=True),
    sa.Column('ms_remediated_status', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('course_grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_grade_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_grade_final_grade'))
        batch_op.drop_index(batch_op.f('ix_course_grade_course_id'))

    op.drop_table('course_grade')
    # ### end Alembic commands ###
