"""Initial migration

Revision ID: c2607f5c06f7
Revises: 
Create Date: 2025-10-04 15:04:24.334229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2607f5c06f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_slot', schema=None) as batch_op:
        batch_op.alter_column('grade_level_id', existing_type=sa.Integer(),
               nullable=False, server_default='1')
        batch_op.create_unique_constraint('_unique_slot_for_grade', ['semester_id', 'grade_level_id', 'day_of_week', 'period_number'])
        batch_op.create_index(batch_op.f('ix_weekly_schedule_slot_grade_level_id'), ['grade_level_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_schedule_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_schedule_slot_grade_level_id'))
        batch_op.drop_constraint('_unique_slot_for_grade', type_='unique')
        batch_op.drop_column('grade_level_id')

    # ### end Alembic commands ###
