"""Add google_credentials_json to User model

Revision ID: d948cbac12b7
Revises: 40277024a952
Create Date: 2025-11-12 17:09:12.862533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd948cbac12b7'
down_revision = '40277024a952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_credentials_json')

    # ### end Alembic commands ###
