"""Add grade submission workflow final fix

Revision ID: e246ef5fbc1e
Revises: 908a62939512
Create Date: 2025-10-11 19:54:54.823624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e246ef5fbc1e'
down_revision = '908a62939512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_submission_status', sa.String(length=50), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('grade_submission_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_course_grade_submission_status'), ['grade_submission_status'], unique=False)
        batch_op.create_foreign_key('fk_course_teacher', 'teacher', ['teacher_id'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('midterm_score')
        batch_op.drop_column('final_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('midterm_score', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_course_grade_submission_status'))
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('grade_submission_notes')
        batch_op.drop_column('grade_submission_status')

    # ### end Alembic commands ###
