"""Add advisor assessment models

Revision ID: fe69ee659143
Revises: b98abac45149
Create Date: 2025-10-16 21:25:03.396995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe69ee659143'
down_revision = 'b98abac45149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_assessment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester_id', name='_student_semester_advisor_assessment_uc')
    )
    with op.batch_alter_table('advisor_assessment_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_assessment_record_advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_assessment_record_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_assessment_record_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_assessment_record_student_id'), ['student_id'], unique=False)

    op.create_table('advisor_assessment_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['advisor_assessment_record.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['assessment_topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'topic_id', name='_record_topic_advisor_score_uc')
    )
    with op.batch_alter_table('advisor_assessment_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_assessment_score_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_assessment_score_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_assessment_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_score_topic_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_score_record_id'))

    op.drop_table('advisor_assessment_score')
    with op.batch_alter_table('advisor_assessment_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_record_student_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_record_status'))
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_record_semester_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_assessment_record_advisor_id'))

    op.drop_table('advisor_assessment_record')
    # ### end Alembic commands ###
